# Dockerfile for mpd

FROM ubuntu:18.04

RUN apt-get -y update
RUN apt-get install -y mpd mpc
RUN /etc/init.d/mpd stop
# RUN killall -9 pulseaudio
RUN /etc/init.d/mpd stop


COPY ./mpd.conf /etc/mpd.conf
COPY ./music/ /var/lib/mpd/music/
VOLUME /var/lib/mpd

EXPOSE 6600
CMD ["mpd", "--stdout", "--no-daemon"]